apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: go-micro-api-jwt
spec:
  targets:
  - name: go-micro-api-sample
  origins:
  - jwt:
      issuer: "testing@secure.istio.io"
      jwksUri: "https://raw.githubusercontent.com/istio/istio/release-1.1/security/tools/jwt/samples/jwks.json"
  principalBinding: USE_ORIGIN