apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: micro-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: micro-api
    spec:
      serviceAccountName: micro-services
      containers:
      - name: api
        command: [
          "/micro",
          "--registry=kubernetes",
          "--server=rpc",
          "--broker=http",
          "--transport=http",
          "--register_ttl=60",
          "--register_interval=30",
          "--selector=cache",
          "--enable_stats",
          "api"
        ]
        image: hbchen/micro:k8s
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: api-port
